'use client'
import { useMemo } from 'react'
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'
import { StatCard } from '@/components/stat-card'
import { useQuestions } from '@/hooks/use-question-store'
import { countBy,quality } from '@/lib/analytics/stats'
import { SimpleBar,SimplePie } from '@/components/charts'
import { BookOpen,CheckCircle2,FileWarning,Languages,PlayCircle } from 'lucide-react'

export default function Analytics(){const {questions}=useQuestions();const q=useMemo(()=>quality(questions),[questions]);const coverage=(n:number)=>questions.length?Math.round(n/questions.length*100):0;return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Analytics</h1><p className="mt-1 text-sm text-slate-500">Live metrics calculated from the currently imported dataset.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><StatCard label="Bilingual Coverage" value={`${coverage(questions.filter(x=>x.bilingualAvailable).length)}%`} icon={<Languages size={18}/>}/><StatCard label="Text Solution Coverage" value={`${coverage(questions.filter(x=>x.textSolutionAvailable).length)}%`} icon={<BookOpen size={18}/>}/><StatCard label="Video Coverage" value={`${coverage(questions.filter(x=>x.videoSolutionAvailable).length)}%`} icon={<PlayCircle size={18}/>}/><StatCard label="Verified Coverage" value={`${coverage(questions.filter(x=>x.verificationStatus.toLowerCase()==='verified').length)}%`} icon={<CheckCircle2 size={18}/>}/><StatCard label="Data Quality Gaps" value={Object.values(q).reduce((a,b)=>a+b,0)} icon={<FileWarning size={18}/>}/></div>{questions.length===0?<Card><CardContent className="py-20 text-center text-slate-500">Import a dataset to populate analytics.</CardContent></Card>:<div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>By Subject</CardTitle></CardHeader><CardContent><SimpleBar data={countBy(questions,'subject')}/></CardContent></Card><Card><CardHeader><CardTitle>By Chapter</CardTitle></CardHeader><CardContent><SimpleBar data={countBy(questions,'chapter')}/></CardContent></Card><Card><CardHeader><CardTitle>By Target Exam</CardTitle></CardHeader><CardContent><SimpleBar data={countBy(questions,'targetExam')}/></CardContent></Card><Card><CardHeader><CardTitle>By Difficulty</CardTitle></CardHeader><CardContent><SimplePie data={countBy(questions,'difficulty')}/></CardContent></Card><Card className="lg:col-span-2"><CardHeader><CardTitle>Data Quality</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Missing subject',q.missingSubject],['Missing chapter',q.missingChapter],['Missing topic',q.missingTopic],['Missing difficulty',q.missingDifficulty],['Missing question',q.missingQuestion],['Missing options',q.missingOptions],['Missing solution',q.missingSolution],['Missing verification',q.missingVerificationStatus]].map(([l,n])=><div key={String(l)} className="rounded-lg border border-slate-200 p-3 dark:border-slate-800"><div className="text-xs text-slate-500">{l}</div><div className="mt-1 text-xl font-semibold">{n as number}</div></div>)}</div></CardContent></Card></div>}</div>}
