'use client'
import { useMemo } from 'react'
import { Filter, RotateCcw, X } from 'lucide-react'
import { useQuestions } from '@/hooks/use-question-store'
import { Button } from './ui/button'
import type { Filters } from '@/types/question'

function values(questions:any[],key:string){return Array.from(new Set(questions.map(q=>q[key]).filter(Boolean))).sort((a,b)=>String(a).localeCompare(String(b)))}
function Multi({label,options,value,onChange}:{label:string;options:string[];value:string[];onChange:(v:string[])=>void}){return <label className="grid gap-1 text-xs text-slate-500"><span>{label}</span><select multiple value={value} onChange={e=>onChange(Array.from(e.target.selectedOptions).map(x=>x.value))} className="min-h-20 rounded-lg border border-slate-200 bg-white p-2 text-sm text-slate-700 outline-none dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200">{options.map(x=><option key={x} value={x}>{x}</option>)}</select></label>}
export function QuestionFilters(){const {questions,filters,setFilters,resetFilters}=useQuestions(); const opts=useMemo(()=>({category:values(questions,'category'),subject:values(questions,'subject'),chapter:values(questions,'chapter'),topic:values(questions,'topic'),subtopic:values(questions,'subtopic'),difficulty:values(questions,'difficulty'),verificationStatus:values(questions,'verificationStatus'),verificationType:values(questions,'verificationType'),questionType:values(questions,'questionType'),targetExam:values(questions,'targetExam'),targetExamStage:Array.from(new Set(questions.flatMap(q=>q.targetExamStages))).sort()}),[questions]); const set=(key:keyof Filters,value:any)=>setFilters(f=>({...f,[key]:value})); const chipValues=(Object.entries(filters) as [keyof Filters,any][]).flatMap(([k,v])=>Array.isArray(v)?v.map(x=>[k,x] as const):[])
 return <div className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><div className="flex items-center gap-2 font-medium"><Filter size={16}/>Advanced filters</div><Button variant="ghost" size="sm" onClick={resetFilters}><RotateCcw size={14}/>Clear all</Button></div>{chipValues.length>0&&<div className="mt-3 flex flex-wrap gap-1.5">{chipValues.map(([k,v])=><button key={`${String(k)}-${v}`} onClick={()=>set(k,(filters[k] as string[]).filter(x=>x!==v))} className="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2.5 py-1 text-xs text-blue-700 dark:bg-blue-950 dark:text-blue-300">{v}<X size={12}/></button>)}</div>}
 <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{([['category','Category'],['subject','Subject'],['chapter','Chapter'],['topic','Topic'],['subtopic','Subtopic'],['difficulty','Difficulty'],['verificationStatus','Verification Status'],['verificationType','Verification Type'],['questionType','Question Type'],['targetExam','Target Exam'],['targetExamStage','Target Exam Stage']] as const).map(([k,l])=><Multi key={k} label={l} options={opts[k]} value={filters[k] as string[]} onChange={v=>set(k,v)}/>)}<label className="grid gap-1 text-xs text-slate-500"><span>Text Solution</span><select value={filters.textSolution} onChange={e=>set('textSolution',e.target.value)} className="h-10 rounded-lg border border-slate-200 px-2 text-sm dark:border-slate-700 dark:bg-slate-900"><option value="all">All</option><option value="yes">Available</option><option value="no">Missing</option></select></label><label className="grid gap-1 text-xs text-slate-500"><span>Video Solution</span><select value={filters.videoSolution} onChange={e=>set('videoSolution',e.target.value)} className="h-10 rounded-lg border border-slate-200 px-2 text-sm dark:border-slate-700 dark:bg-slate-900"><option value="all">All</option><option value="yes">Available</option><option value="no">Missing</option></select></label><label className="grid gap-1 text-xs text-slate-500"><span>Bilingual</span><select value={filters.bilingual} onChange={e=>set('bilingual',e.target.value)} className="h-10 rounded-lg border border-slate-200 px-2 text-sm dark:border-slate-700 dark:bg-slate-900"><option value="all">All</option><option value="yes">Available</option><option value="no">Missing</option></select></label><label className="grid gap-1 text-xs text-slate-500"><span>Updated From</span><input type="date" value={filters.updatedFrom} onChange={e=>set('updatedFrom',e.target.value)} className="h-10 rounded-lg border border-slate-200 px-2 text-sm dark:border-slate-700 dark:bg-slate-900"/></label><label className="grid gap-1 text-xs text-slate-500"><span>Updated To</span><input type="date" value={filters.updatedTo} onChange={e=>set('updatedTo',e.target.value)} className="h-10 rounded-lg border border-slate-200 px-2 text-sm dark:border-slate-700 dark:bg-slate-900"/></label></div></div> }
