'use client'
import { useEffect } from 'react'
import { X, Copy, ExternalLink, Video } from 'lucide-react'
import { Button } from './ui/button'
import { Badge } from './ui/badge'
import { CopyButton } from './question-actions'
import { dateDisplay } from '@/lib/utils/parse'
import { sanitizeHtml } from '@/lib/utils/sanitize'
import type { NormalizedQuestion } from '@/types/question'

const statusVariant=(s:string)=>s.toLowerCase()==='verified'?'success':s.toLowerCase()==='pending'?'warning':s.toLowerCase()==='unverified'?'danger':'muted'
export function QuestionDetail({q,onClose}:{q:NormalizedQuestion;onClose?:()=>void}){useEffect(()=>{const h=(e:KeyboardEvent)=>e.key==='Escape'&&onClose?.();window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[onClose]); const copyHtml=(label:string,html:string)=>navigator.clipboard.writeText(html.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim())
 const meta=[['Category',q.category],['Subject',q.subject],['Chapter',q.chapter],['Topic',q.topic],['Subtopic',q.subtopic],['Class',q.className],['Book',q.book],['QCM Tag',q.qcmTag],['Target Exam',q.targetExam],['Target Exam Stage',q.targetExamStages.join(', ')],['Question Type',q.questionType],['Verification Type',q.verificationType],['Difficulty',q.difficulty],['Verification Status',q.verificationStatus],['Bilingual Content Count',q.bilingualContentCount],['Bilingual Solution Count',q.bilingualSolutionCount],['Parent Question ID',q.parentQuestionId],['Category Configuration ID',q.categoryConfigurationId],['Updated At',dateDisplay(q.updatedAt)]]
 return <div className="relative mx-auto max-w-6xl"><div className="sticky top-0 z-10 border-b border-slate-200 bg-slate-50/95 py-4 backdrop-blur dark:border-slate-800 dark:bg-slate-950/95"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-sm font-semibold">{q.id}</span><CopyButton value={q.id} label="QBG ID"/><Badge variant={statusVariant(q.verificationStatus)}>{q.verificationStatus||'Unknown'}</Badge>{q.difficulty&&<Badge variant="muted">Difficulty {q.difficulty}</Badge>}</div><p className="mt-1 text-xs text-slate-500">Updated {dateDisplay(q.updatedAt)}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>copyHtml('English question',q.englishQuestion)}><Copy size={14}/>Copy Question</Button><Button variant="outline" size="sm" onClick={()=>copyHtml('English solution',q.englishSolution)}><Copy size={14}/>Copy Solution</Button>{onClose&&<Button variant="ghost" size="sm" onClick={onClose}><X size={18}/></Button>}</div></div></div>
 <div className="grid gap-6 py-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-6"><section className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">English Question</h2><CopyButton value={q.englishQuestion.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()} label="English question"/></div><div className="prose-q text-[15px]" dangerouslySetInnerHTML={{__html:sanitizeHtml(q.englishQuestion)||'<span>No English question available.</span>'}} />{q.hindiQuestion&&<><hr className="my-6 border-slate-200 dark:border-slate-800"/><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">Hindi Question</h2><CopyButton value={q.hindiQuestion.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()} label="Hindi question"/></div><div className="prose-q text-[15px]" dangerouslySetInnerHTML={{__html:sanitizeHtml(q.hindiQuestion)}} /></>}</section>
 {q.englishOptions.length>0&&<section className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">Options</h2><div className="mt-3 grid gap-2">{q.englishOptions.map(o=><div key={o.label} className={`flex gap-3 rounded-lg border p-3 ${o.correct?'border-green-300 bg-green-50 dark:border-green-800 dark:bg-green-950/30':'border-slate-200 dark:border-slate-800'}`}><span className="font-semibold">{o.label}.</span><div className="prose-q" dangerouslySetInnerHTML={{__html:sanitizeHtml(o.text)}} />{o.correct&&<Badge variant="success" className="ml-auto">Correct</Badge>}</div>)}</div></section>}
 <section className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">Solution</h2>{q.englishSolution&&<CopyButton value={q.englishSolution.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()} label="English solution"/>}</div><p className="mb-3 text-xs text-slate-500">Text Solution: <b>{q.textSolutionAvailable?'Available':'Not Available'}</b> · Video Solution: <b>{q.videoSolutionAvailable?'Available':'Not Available'}</b></p>{q.englishSolution?<div className="prose-q" dangerouslySetInnerHTML={{__html:sanitizeHtml(q.englishSolution)}}/>:<div className="text-sm text-slate-500">No text solution available.</div>}{q.hindiSolution&&<><hr className="my-6 border-slate-200 dark:border-slate-800"/><h3 className="mb-2 font-medium">Hindi Solution</h3><div className="prose-q" dangerouslySetInnerHTML={{__html:sanitizeHtml(q.hindiSolution)}}/></>}{q.videoUrls.length>0&&<div className="mt-5 flex flex-wrap gap-2">{q.videoUrls.map((u,i)=><a key={u} href={u} target="_blank" rel="noreferrer"><Button variant="outline" size="sm"><Video size={14}/>Watch Video {q.videoUrls.length>1?i+1:''}<ExternalLink size={12}/></Button></a>)}</div>}</section></div>
 <aside className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">Metadata</h2><dl className="mt-4 space-y-3">{meta.filter(([,v])=>String(v??'').trim()!=='').map(([k,v])=><div key={k}><dt className="text-xs text-slate-400">{k}</dt><dd className="mt-0.5 break-words text-sm">{String(v)}</dd></div>)}</dl></aside></div></div>
}
