'use client'
import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'
import type { Filters, NormalizedQuestion } from '@/types/question'

const DB_NAME='question-backend'; const STORE='questions'; const DB_VERSION=1
const defaultFilters: Filters = { category:[],subject:[],chapter:[],topic:[],subtopic:[],difficulty:[],verificationStatus:[],verificationType:[],questionType:[],targetExam:[],targetExamStage:[],textSolution:'all',videoSolution:'all',bilingual:'all',updatedFrom:'',updatedTo:'' }
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function loadRows(){const db=await openDb();return new Promise<NormalizedQuestion[]>((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).getAll();req.onsuccess=()=>resolve(req.result??[]);req.onerror=()=>reject(req.error)})}
async function saveRows(rows:NormalizedQuestion[]){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');const os=tx.objectStore(STORE);os.clear();for(const row of rows) os.put(row);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
function matchText(q: NormalizedQuestion, term: string) { const haystack=[q.id,q.englishQuestion,q.hindiQuestion,q.subject,q.chapter,q.topic,q.subtopic,q.category,q.targetExam,q.qcmTag].join(' ').toLowerCase(); return haystack.includes(term.toLowerCase()) }
function inArr(value:string, filter:string[]) { return !filter.length || filter.includes(value) }
function inArrMulti(values:string[], filter:string[]) { return !filter.length || values.some(v => filter.includes(v)) }
interface Ctx { questions: NormalizedQuestion[]; setQuestions:(q:NormalizedQuestion[])=>void; filters:Filters; setFilters:React.Dispatch<React.SetStateAction<Filters>>; search:string; setSearch:React.Dispatch<React.SetStateAction<string>>; filtered:NormalizedQuestion[]; resetFilters:()=>void; dataSource:'local'|'supabase'; clearData:()=>void }
const Store=createContext<Ctx|null>(null)
export function QuestionProvider({children}:{children:React.ReactNode}){const [questions,setQuestionsState]=useState<NormalizedQuestion[]>([]);const [filters,setFilters]=useState<Filters>(defaultFilters);const [search,setSearch]=useState('');const [ready,setReady]=useState(false);useEffect(()=>{loadRows().then(setQuestionsState).catch(()=>setQuestionsState([])).finally(()=>setReady(true))},[]);const setQuestions=(rows:NormalizedQuestion[])=>{setQuestionsState(rows);saveRows(rows).catch(()=>{})};const filtered=useMemo(()=>questions.filter(q=>{if(search&&!matchText(q,search))return false;if(!inArr(q.category,filters.category)||!inArr(q.subject,filters.subject)||!inArr(q.chapter,filters.chapter)||!inArr(q.topic,filters.topic)||!inArr(q.subtopic,filters.subtopic))return false;if(!inArr(q.difficulty,filters.difficulty)||!inArr(q.verificationStatus,filters.verificationStatus)||!inArr(q.verificationType,filters.verificationType)||!inArr(q.questionType,filters.questionType)||!inArr(q.targetExam,filters.targetExam)||!inArrMulti(q.targetExamStages,filters.targetExamStage))return false;if(filters.textSolution!=='all'&&(q.textSolutionAvailable?'yes':'no')!==filters.textSolution)return false;if(filters.videoSolution!=='all'&&(q.videoSolutionAvailable?'yes':'no')!==filters.videoSolution)return false;if(filters.bilingual!=='all'&&(q.bilingualAvailable?'yes':'no')!==filters.bilingual)return false;const t=q.updatedAt?new Date(q.updatedAt).getTime():NaN;if(filters.updatedFrom&&(!Number.isFinite(t)||t<new Date(filters.updatedFrom).getTime()))return false;if(filters.updatedTo&&(!Number.isFinite(t)||t>new Date(filters.updatedTo+'T23:59:59').getTime()))return false;return true}),[questions,filters,search]);const resetFilters=()=>setFilters(defaultFilters);const clearData=()=>{setQuestionsState([]);indexedDB.databases?.().then(()=>openDb()).then(db=>new Promise<void>((resolve)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=()=>resolve()})).catch(()=>{}) ;setFilters(defaultFilters);setSearch('')};return <Store.Provider value={{questions,setQuestions,filters,setFilters,search,setSearch,filtered,resetFilters,dataSource:'local',clearData}}>{ready?children:children}</Store.Provider>}
export function useQuestions(){const ctx=useContext(Store);if(!ctx)throw new Error('useQuestions must be inside QuestionProvider');return ctx}
