'use client'
import Link from 'next/link'
import { CheckCircle2, CircleAlert, FileText, Languages, PlayCircle, Database, ArrowRight } from 'lucide-react'
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'
import { StatCard } from '@/components/stat-card'
import { useQuestions } from '@/hooks/use-question-store'
import { countBy } from '@/lib/analytics/stats'
import { SimpleBar,SimplePie } from '@/components/charts'
import { dateDisplay } from '@/lib/utils/parse'

export default function Dashboard(){const {questions}=useQuestions();const verified=questions.filter(q=>q.verificationStatus.toLowerCase()==='verified').length;const recent=[...questions].filter(q=>q.updatedAt).sort((a,b)=>new Date(b.updatedAt!).getTime()-new Date(a.updatedAt!).getTime()).slice(0,8); return <div className="space-y-6"><div><h1 className="text-2xl font-semibold tracking-tight">Question Backend</h1><p className="mt-1 text-sm text-slate-500">Your internal question-bank command center.</p></div>{!questions.length&&<Card className="border-dashed"><CardContent className="flex flex-col items-center justify-center py-16 text-center"><div className="rounded-full bg-blue-50 p-4 text-blue-600 dark:bg-blue-950"><Database size={24}/></div><h2 className="mt-4 text-lg font-semibold">Import your question bank</h2><p className="mt-1 max-w-md text-sm text-slate-500">Upload the raw Excel/CSV backend file to populate KPIs, search, filters, analytics and question detail pages.</p><Link href="/upload" className="mt-5 inline-flex h-10 items-center gap-2 rounded-lg bg-blue-600 px-4 text-sm font-medium text-white">Go to Upload <ArrowRight size={15}/></Link></CardContent></Card>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><StatCard label="Total Questions" value={questions.length} icon={<Database size={18}/>}/><StatCard label="Verified" value={verified} icon={<CheckCircle2 size={18}/>}/><StatCard label="Unverified" value={questions.filter(q=>q.verificationStatus.toLowerCase()==='unverified').length} icon={<CircleAlert size={18}/>}/><StatCard label="Text Solution" value={questions.filter(q=>q.textSolutionAvailable).length} icon={<FileText size={18}/>}/><StatCard label="Video Solution" value={questions.filter(q=>q.videoSolutionAvailable).length} icon={<PlayCircle size={18}/>}/><StatCard label="Bilingual" value={questions.filter(q=>q.bilingualAvailable).length} icon={<Languages size={18}/>}/></div>
 {questions.length>0&&<><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Questions by Subject</CardTitle></CardHeader><CardContent><SimpleBar data={countBy(questions,'subject')}/></CardContent></Card><Card><CardHeader><CardTitle>Questions by Category</CardTitle></CardHeader><CardContent><SimplePie data={countBy(questions,'category')}/></CardContent></Card><Card><CardHeader><CardTitle>Difficulty Distribution</CardTitle></CardHeader><CardContent><SimpleBar data={countBy(questions,'difficulty')}/></CardContent></Card><Card><CardHeader><CardTitle>Verification Status</CardTitle></CardHeader><CardContent><SimplePie data={countBy(questions,'verificationStatus')}/></CardContent></Card></div><Card><CardHeader><CardTitle>Questions by Target Exam</CardTitle></CardHeader><CardContent><SimpleBar data={countBy(questions,'targetExam')}/></CardContent></Card><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Recent Questions</CardTitle><Link href="/questions" className="text-sm text-blue-600">View all</Link></CardHeader><CardContent><div className="divide-y divide-slate-100 dark:divide-slate-800">{recent.map(q=><Link href={`/questions/${encodeURIComponent(q.id)}`} key={q.id} className="flex items-center justify-between gap-4 py-3 hover:bg-slate-50 dark:hover:bg-slate-800/50"><div className="min-w-0"><div className="font-mono text-xs text-blue-600">{q.id}</div><div className="truncate text-sm font-medium">{q.englishQuestion.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').slice(0,140)||'No question text'}</div></div><div className="shrink-0 text-xs text-slate-400">{dateDisplay(q.updatedAt)}</div></Link>)}</div></CardContent></Card></>}</div>}
